# Generated by Django 5.1.5 on 2025-01-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Zapatillas', 'Zapatillas'), ('Ropa', 'Ropa'), ('Accesorios', 'Accesorios')], default='Zapatillas', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Niños', 'Niños'), ('Unisex', 'Unisex')], default='Unisex', max_length=50, verbose_name='Género'),
        ),
    ]
