# Generated by Django 5.1.1 on 2025-06-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='versions',
        ),
        migrations.DeleteModel(
            name='CarVersion',
        ),
    ]
