# Generated by Django 5.1.1 on 2025-06-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_versions_delete_carversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcar',
            name='image',
        ),
    ]
