# Generated by Django 5.1.5 on 2025-08-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_modelcar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcar',
            name='marca',
            field=models.CharField(blank=True, choices=[('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Volkswagen', 'Volkswagen'), ('Toyota', 'Toyota'), ('Renault', 'Renault'), ('Peugeot', 'Peugeot'), ('Nissan', 'Nissan'), ('Mazda', 'Mazda'), ('Mercedes', 'Mercedes'), ('Honda', 'Honda')], max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AddConstraint(
            model_name='modelcar',
            constraint=models.UniqueConstraint(fields=('marca', 'name'), name='uniq_model_per_brand'),
        ),
    ]
